### ISSUE TITLE
latencylingo website is down

### ISSUE THREAD

**Issue by yyahav** [AnthonyBobsin/latency-lingo-cli#3]
@AnthonyBobsin Hi, I'm notifying here as I can't find other way to contact you.
LatencyLingo website is down:
<img width="446" alt="image" src="https://github.com/latency-lingo/cli/assets/88027106/8b286a9d-3a70-4422-b54a-0fcb54d936a9">

Can you please handle it?

**Comment by AnthonyBobsin** [comment]
@yyahav thank you for reporting! I've taken action and am waiting for DNS to update and resolve the issue. I'll send you an update once available again

**Comment by AnthonyBobsin** [comment]
Site is back up. Thanks again for reporting! Closing issue

**Comment by yyahav** [comment]
Thank you for the quick response @AnthonyBobsin ! 
I also sent an email to support regarding another issue I faced, could you have a look?
